#!/bin/sh

source /etc/portage/hooks/functions/check-env.sh

instprep() {

    rm -f "${D}/usr/bin/nvidia-bug-report.sh" || true
    rm -f "${D}/opt/bin/nvidia-xconfig" || true
    rm -f "${D}/opt/bin/nvidia-persistenced" || true

    rm -f "${D}/usr/bin/nvidia-xconfig" || true
    rm -f "${D}/usr/bin/nvidia-persistenced" || true

    rm -f "${D}/etc/conf.d/nvidia-persistenced" || true
    rm -f "${D}/etc/init.d/nvidia-persistenced" || true
    rm -f "${D}/etc/nvidia/nvidia-application-profiles-rc" || true
    rm -rf "${D}/etc/X11/xinit" || true

    rm -rf "${D}/usr/share/applications" || true
    rm -rf "${D}/usr/share/pixmaps" || true
    #rm -rf "${D}/usr/share/nvidia" || true

    rm -rf "${D}/usr/share/doc" || true

    #mkdir -p "${D}/opt/nvidia-tools"
    #mv "${D}/usr/bin/nvidia-settings" "${D}/opt/nvidia-tools/"
}

case "$1" in
    instprep) instprep ;;
    *) : ;;
esac
