#!/bin/sh

# out of line patch to remove desktop file processing in
# eselect-wine, otherwise it complains with an error and
# just dies leaving a lot of dangling and incorrect symlinks
# in place
# i didn't managed to get this patch to apply inside
# /etc/portage/patches
# so i implemented this hook which modifies the install image
# before merging it into the system

instprep() {
    cd "$ED/usr/share/eselect/modules"
    patch wine.eselect < /etc/portage/hooks/patches/app-eselect/eselect-wine/remove-desktop-support.diff
}

case "$1" in
    instprep) instprep ;;
    *) : ;;
esac
