#!/bin/sh

instprep() {
    echo "Patching vmware-vmx to use absolute paths to bundled GCC runtime libraries..."

    cd "${ED}/opt/vmware/lib/vmware/bin"
    patchelf --replace-needed libstdc++.so.6 /opt/vmware/lib/vmware/lib/libstdc++.so.6/libstdc++.so.6 vmware-vmx
    patchelf --replace-needed libgcc_s.so.1 /opt/vmware/lib/vmware/lib/libgcc_s.so.1/libgcc_s.so.1 vmware-vmx
}

case "$1" in
    instprep) instprep ;;
    *) : ;;
esac
