#!/bin/sh

postinst() {
    # remove useless desktop files I don't want and use
    # this is not how wine should be used
    # binfmt.d integration is already disabled with a USE flag
    echo -e ">>> Removing wine desktop files..."
    rm -f /usr/share/applications/wine-browsedrive.desktop
    rm -f /usr/share/applications/wine-notepad.desktop
    rm -f /usr/share/applications/wine-uninstaller.desktop
    rm -f /usr/share/applications/wine-vanilla.desktop
    rm -f /usr/share/applications/wine-winecfg.desktop
    rm -f /usr/share/applications/wine.desktop

    # run winetricks hook, just in case™
    /etc/portage/hooks/app-emulation/winetricks postinst
}

case "$1" in
    postinst) postinst ;;
    *) : ;;
esac
