#!/bin/sh

. /etc/portage/hooks/functions/desktop-utils.sh

instprep() {
    echo -e ">>> Removing ${PN} desktop files..."
    remove_desktop_files

    if [ ! -z "$ED" ]; then
        rm -r "$ED/usr/share/${PN}-${PV}/applications"
    fi
}

postinst() {
    # remove useless desktop files I don't want and use
    # this is not how wine should be used
    # binfmt.d integration is already disabled with a USE flag
    echo -e ">>> Removing ${PN} desktop files..."
    rm -f /usr/share/applications/wine-browsedrive.desktop
    rm -f /usr/share/applications/wine-notepad.desktop
    rm -f /usr/share/applications/wine-uninstaller.desktop
    rm -f /usr/share/applications/wine-vanilla.desktop
    rm -f /usr/share/applications/wine-winecfg.desktop
    rm -f /usr/share/applications/wine.desktop
}

case "$1" in
    instprep) instprep ;;
    postinst) postinst ;;
    *) : ;;
esac
