#!/bin/sh

postinst() {
    echo -e ">>> Removing winetricks desktop files..."
    rm -f /usr/share/applications/winetricks.desktop

    # run wine hook, just in case™
    /etc/portage/hooks/app-emulation/wine-vanilla postinst
}

case "$1" in
    postinst) postinst ;;
    *) : ;;
esac
