#!/bin/sh

source /etc/portage/hooks/functions/check-env.sh

. /etc/portage/hooks/functions/desktop-utils.sh

instprep() {
    echo -e ">>> Removing ${PN} desktop files..."
    remove_desktop_files
}

postinst() {
    echo -e ">>> Removing ${PN} desktop files..."
    rm -f /usr/share/applications/uxterm.desktop
    rm -f /usr/share/applications/xterm.desktop
}

case "$1" in
    instprep) instprep ;;
    postinst) postinst ;;
    *) : ;;
esac
