#!/bin/sh

postinst() {
    echo -e ">>> Removing xterm desktop files..."
    rm -f /usr/share/applications/uxterm.desktop
    rm -f /usr/share/applications/xterm.desktop
}

case "$1" in
    postinst) postinst ;;
    *) : ;;
esac
