#!/bin/sh

source /etc/portage/hooks/functions/check-env.sh

configure() {
    cd "$S"
    patch -p1 < /etc/portage/patches/sys-fs/xfsprogs/disable-lto.patch
}

case "$1" in
    configure) configure ;;
    *) : ;;
esac
