#!/bin/sh

source /etc/portage/hooks/functions/check-env.sh

. /etc/portage/hooks/functions/delete-vcs.sh

prepare() {
    remove_vcs git

    # apply clang patches
    pushd "${S}"
    for PATCH in /etc/portage/hooks/patches/sys-devel/clang/*.patch; do
        echo -e "\e[1m === Applying clang patch ${PATCH}...\e[0m"
        patch --verbose -p1 < "$PATCH"
    done
    popd

    # apply clang-tools-extra patches
    pushd "${S}/../clang-tools-extra"
    for PATCH in /etc/portage/hooks/patches/sys-devel/clang/clangd/*.patch; do
        echo -e "\e[1m === Applying clang-tools-extra patch ${PATCH}...\e[0m"
        patch --verbose -p1 < "$PATCH"
    done
    popd
}

case "$1" in
    prepare) prepare ;;
    *) : ;;
esac
