#!/bin/sh

show_config_toml() {
    cat config.toml || exit 1
}

# fix the compiler in config.toml to replace libgcc_s with libunwind and enable POSIX extensions
compile() {

    # cd into directory and show current config.toml
    cd "$S/../rustc-$PV-src"
    show_config_toml

    # apply config.toml patch and show it again
    echo -e "\e[1mPatching config.toml...\e[0m"
    #patch -p1 < /etc/portage/hooks/patches/dev-lang/rust/fix-config-toml-multilib.patch || exit 1
    patch -p1 < /etc/portage/hooks/patches/dev-lang/rust/fix-config-toml.patch || exit 1
    show_config_toml

    echo -e "\e[1m───────────────────────────────────────────────────────────\e[0m"
}

case "$1" in
    compile) compile ;;
    *) : ;;
esac
