#!/bin/sh

prepare() {
    # remove tests
    rm -r "../work/${P}/tests"

    # remove version file (conflicts with LLVM/libc++)
    rm "../work/${P}/version"
}

case "$1" in
    prepare) prepare ;;
    *) : ;;
esac
