#!/bin/sh

# remove compiled bytecode, because there are no docstrings
# anymore which makes yacc unhappy and dies with:
# "ERROR: start symbol translation_unit_or_empty undefined"

instprep() {
    if [ ! -z "${D}" ]; then
        echo "Removing bytecode to prevent problems with Yacc..."

        # python 3.7
        rm -rf "${D}/usr/lib/python3.7/site-packages/pycparser/__pycache__/"
        rm -rf "${D}/usr/lib/python3.7/site-packages/pycparser/ply/__pycache__/"

        # python 3.9
        rm -rf "${D}/usr/lib/python3.9/site-packages/pycparser/__pycache__/"
        rm -rf "${D}/usr/lib/python3.9/site-packages/pycparser/ply/__pycache__/"
    fi
}

case "$1" in
    instprep) instprep ;;
    *) : ;;
esac
