#!/bin/sh

source /etc/portage/hooks/functions/check-env.sh

instprep() {
    echo "remove unused xdg autostart files..."
    rm "${ED}/etc/xdg/autostart/gnome-keyring-pkcs11.desktop"
    rm "${ED}/etc/xdg/autostart/gnome-keyring-ssh.desktop"

    echo "remove pkcs11 module..."
    rm -r "${ED}/usr/lib64/pkcs11"
}

case "$1" in
    instprep) instprep ;;
    *) : ;;
esac
