#!/bin/sh

instprep() {
    echo -e ">>> Removing default config (only use my own profiles)..."
    if [ ! -z "${ED}" ]; then
        rm -r "${ED}/etc/firejail"
    fi
}

case "$1" in
    instprep) instprep ;;
    *) : ;;
esac
