#!/bin/sh

source /etc/portage/hooks/functions/check-env.sh

instprep() {
    if [ ! -z "${D}" ]; then
        echo "Remove search providers..."
        rm "${D}/usr/share/kf6/searchproviders/"*

        echo "Remove trash bin..."
        rm "${D}/usr/share/applications/kcm_trash.desktop"

        # TODO: verify if these files are still present
        rm -f "${D}/usr/bin/ktrash6"
        rm -f "${D}/usr/lib64/qt6/plugins/kcm_trash.so"
        rm -f "${D}/usr/lib64/qt6/plugins/kf6/kio/trash.so"
        rm -f "${D}/usr/lib64/qt6/plugins/kf6/kio/kio_trash.so"
        rm -f "${D}/usr/share/kservices6/kcmtrash.desktop"
    fi
}

case "$1" in
    instprep) instprep ;;
    *) : ;;
esac
