#!/bin/sh

instprep() {
    if [ ! -z "${D}" ]; then
        echo "Remove search providers..."
        rm "${D}/usr/share/kservices5/searchproviders/"*

        echo "Remove trash bin..."
        rm "${D}/usr/bin/ktrash5"
        rm "${D}/usr/lib64/qt5/plugins/kcm_trash.so"
        rm "${D}/usr/lib64/qt5/plugins/kf5/kio/trash.so"
        rm "${D}/usr/share/kservices5/kcmtrash.desktop"
    fi
}

case "$1" in
    instprep) instprep ;;
    *) : ;;
esac
