#!/bin/sh

source /etc/portage/hooks/functions/check-env.sh

instprep() {
    if [ ! -z "${D}" ]; then
        echo "Remove unneeded plugins from DNS blocked services..."

        rm "${D}/usr/lib64/qt6/plugins/kf6/purpose/imgurplugin.so"
        rm "${D}/usr/lib64/qt6/plugins/kf6/purpose/pastebinplugin.so"
        rm "${D}/usr/lib64/qt6/plugins/kf6/purpose/telegramplugin.so"
    fi
}

case "$1" in
    instprep) instprep ;;
    *) : ;;
esac
