#!/bin/sh

source /etc/portage/hooks/functions/check-env.sh

instprep() {
    if [ ! -z "${D}" ]; then
        echo "Remove trash bin..."
        rm -r "${D}/usr/lib64/qt6/qml/org/kde/plasma/private/trash"
        rm -r "${D}/usr/share/plasma/plasmoids/org.kde.plasma.trash"
        
        rm "${D}/usr/share/kservices6/plasma-applet-org.kde.plasma.trash.desktop"
        rm "${D}/usr/share/metainfo/org.kde.plasma.trash.appdata.xml"
    fi
}

case "$1" in
    instprep) instprep ;;
    *) : ;;
esac
