#!/bin/sh

source /etc/portage/hooks/functions/check-env.sh

instprep() {
    echo "Create custom launcher to inject GCC runtime libraries and dGPU launcher..."

    cd "${ED}/usr/bin"
    rm brave-bin
    cp /etc/portage/hooks/patches/www-client/brave-bin/brave.sh brave-bin
    chmod +x brave-bin
}

case "$1" in
    instprep) instprep ;;
    *) : ;;
esac
