#!/bin/sh

source /etc/portage/hooks/functions/check-env.sh

instprep() {
    # NOTE: patching of product.json not required

    echo "Injecting GCC runtime libraries into launcher script..."
    cd "${ED}/opt/vscode/bin"
    patch -p1 < /etc/portage/hooks/patches/app-editors/vscodium/vscode-gnu-runtime-libs.patch

    echo "Use dGPU for rendering..."
    patch -p1 < /etc/portage/hooks/patches/app-editors/vscodium/vscode-use-dgpu-for-rendering.patch

    echo "Patching workbench.html to allow injecting custom CSS..."
    cd "${ED}/opt/vscode/resources/app/out/vs/code/electron-sandbox/workbench"
    patch workbench.html < /etc/portage/hooks/patches/app-editors/vscodium/workbench-custom-css.patch

    cp /etc/portage/hooks/patches/app-editors/vscodium/custom.css \
        "${ED}/opt/vscode/custom.css"
    cp /etc/portage/hooks/patches/app-editors/vscodium/custom.js \
        "${ED}/opt/vscode/custom.js"

   cd "${ED}/opt/vscode/resources/app/out/vs/workbench"
   ln -s ../../../../../custom.css .
   ln -s ../../../../../custom.js .

   ln -s ../../../../../../vscodium-assets .

   # remove wayland desktop files
   #rm -f "${ED}/usr/share/applications/vscode-url-handler-wayland.desktop"
   #rm -f "${ED}/usr/share/applications/vscode-wayland.desktop"
}

postinst() {
    echo "adjust /opt/vscode/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html"
}

case "$1" in
    instprep) instprep ;;
    postinst) postinst ;;
    *) : ;;
esac
