#!/bin/sh

source /etc/portage/hooks/functions/check-env.sh

instprep() {
    # NOTE: patching of product.json not required

    echo "Injecting GCC runtime libraries into launcher script..."
    cd "${ED}/opt/vscode/bin"
    patch -p1 < /etc/portage/hooks/patches/app-editors/vscodium/vscode-gnu-runtime-libs.patch

    # NOTE: I swapped GPUs in the UEFI settings, dGPU default, primerun -> iGPU
    #echo "Use dGPU for rendering..."
    #patch -p1 < /etc/portage/hooks/patches/app-editors/vscodium/vscode-use-dgpu-for-rendering.patch

    # NOTE: required for the Wayland session, as enabling GTK_USE_PORTAL=1 in Wayland causes major problems with GTK applications
    echo "Use KDE file dialogs..."
    patch -p1 < /etc/portage/hooks/patches/app-editors/vscodium/vscode-use-kde-file-dialogs.patch

    echo "Patching workbench.esm.html to allow injecting custom CSS..."
    cd "${ED}/opt/vscode/resources/app/out/vs/code/electron-sandbox/workbench"
    patch workbench.esm.html < /etc/portage/hooks/patches/app-editors/vscodium/workbench-custom-css.patch

    cp /etc/portage/hooks/patches/app-editors/vscodium/custom.css \
        "${ED}/opt/vscode/custom.css"
    cp /etc/portage/hooks/patches/app-editors/vscodium/custom.js \
        "${ED}/opt/vscode/custom.js"

   cd "${ED}/opt/vscode/resources/app/out/vs/workbench"
   ln -s ../../../../../custom.css .
   ln -s ../../../../../custom.js .

   ln -s ../../../../../../vscodium-assets .

   # remove wayland desktop files
   #rm -f "${ED}/usr/share/applications/vscode-url-handler-wayland.desktop"
   #rm -f "${ED}/usr/share/applications/vscode-wayland.desktop"
}

postinst() {
    echo "adjust /opt/vscode/resources/app/out/vs/code/electron-sandbox/workbench/workbench.esm.html"
}

case "$1" in
    instprep) instprep ;;
    postinst) postinst ;;
    *) : ;;
esac
