#!/bin/sh

source /etc/portage/hooks/functions/check-env.sh

instprep() {
    cd "${ED}"

    echo "Preparing ClamAV for minimal usage..."

    # remove daemon, only use command line scanner
    rm "${ED}/usr/sbin/clamd"
    rmdir "${ED}/usr/sbin"
    rm "${ED}/usr/bin/clamdscan"

    # remove service files
    rm -r "${ED}/etc/init.d"
    rm -r "${ED}/lib/systemd"

    # remove header files and pkg-config, so nothing can accidentally depend on it
    rm -r "${ED}/usr/lib64/pkgconfig"
    rm -r "${ED}/usr/include"
}

case "$1" in
    instprep) instprep ;;
    *) : ;;
esac
