#!/bin/sh

source /etc/portage/hooks/functions/check-env.sh

instprep() {
    if [ ! -z "${D}" ]; then
        echo "Remove Solid actions..."

        rm -r "${D}/usr/share/solid"
    fi
}

case "$1" in
    instprep) instprep ;;
    *) : ;;
esac
