#!/bin/sh

source /etc/portage/hooks/functions/check-env.sh

instprep() {
    if [ ! -z "${D}" ]; then
        echo "Remove Google..."

        #rm "${D}/usr/bin/akonadi_googlecalendar_resource"
        #rm "${D}/usr/bin/akonadi_googlecontacts_resource"
        #rm "${D}/usr/share/akonadi/agents/googlecalendarresource.desktop"
        #rm "${D}/usr/share/akonadi/agents/googlecontactsresource.desktop"

        rm -f "${D}/usr/bin/akonadi_google_resource"
        rm -f "${D}/usr/share/akonadi/agents/googleresource.desktop"
    fi
}

case "$1" in
    instprep) instprep ;;
    *) : ;;
esac
