#!/bin/sh

instprep_old() {
    local electron_slot=5.0

    if [ ! -z "${D}" ]; then
        echo "Copying Electron as Riot..."

        cp -rp "/opt/electron-${electron_slot}" "${D}/usr/libexec/riot/electron"
        mv "${D}/usr/libexec/riot/electron/electron" "${D}/usr/libexec/riot/electron/Riot"

        echo -e "#"'!'"/bin/sh\n\nexec /usr/libexec/riot/electron/Riot /usr/libexec/riot/ \"\$@\"" > \
            "${D}/usr/bin/riot-desktop"
        chmod +x "${D}/usr/bin/riot-desktop"
    fi
}

instprep() {
    cd "${D}/opt/Element/resources"
    /opt/nodejs/pkg/bin/asar e app.asar app
    /opt/nodejs/pkg/bin/asar e webapp.asar webapp
    rm app.asar
    rm webapp.asar
    cp /etc/portage/hooks/patches/net-im/riot-desktop/custom.css webapp/custom.css

    # create version file so it doesn't show "unknown"
    echo -en "${PV}" > webapp/version
}

compile() {
    echo "Fix monospace fonts not working in Electron app..."
    cd "${S}/../element-web-${PV}"
    patch -p1 < /etc/portage/hooks/patches/net-im/riot-desktop/no-markdown-font-important.patch
}

case "$1" in
    instprep) instprep ;;
    compile) compile ;;
    *) : ;;
esac
