#!/bin/sh

instprep() {
    local electron_slot=5.0

    if [ ! -z "${D}" ]; then
        echo "Copying Electron as Riot..."

        cp -rp "/opt/electron-${electron_slot}" "${D}/usr/libexec/riot/electron"
        mv "${D}/usr/libexec/riot/electron/electron" "${D}/usr/libexec/riot/electron/Riot"

        echo -e "#"'!'"/bin/sh\n\nexec /usr/libexec/riot/electron/Riot /usr/libexec/riot/ \"\$@\"" > \
            "${D}/usr/bin/riot-desktop"
        chmod +x "${D}/usr/bin/riot-desktop"
    fi
}

compile() {
    echo "Fix monospace fonts not working in Electron app..."
    cd "${S}"
    patch -p1 < /etc/portage/hooks/patches/net-im/riot-desktop/no-markdown-font-important.patch
}

case "$1" in
    instprep) instprep ;;
    compile) compile ;;
    *) : ;;
esac
