#!/bin/sh

# removes offending -latomic arguments from the compiler invocation

CLANG="$(basename "$0")"
args=()

if [[ "$CLANG" == *"++" ]]; then
    REAL_CLANG=clang++
else
    REAL_CLANG=clang
fi

for x in "$@"; do
    if [[ "$x" == *"-latomic"* ]]; then
        :
    else
        args+=("$x")
    fi
done

exec "$REAL_CLANG" "${args[@]}"
