#!/bin/bash

ld="$(basename "$0")"
args=()

# replace GNU with LLVM
for x in "$@"; do
    if [[ "$x" == *"-lstdc++"* ]]; then
        args+=("-lc++")
    elif [[ "$x" == *"-lgcc_s"* ]]; then
        args+=("-lunwind")
    else
        args+=("$x")
    fi
done

# invoice real clang with modified arguments
exec "clang" -D_GNU_SOURCE "${args[@]}"
