#!/bin/sh

# remove binaries and daemons
# only keep libraries for some precompiled stuff which needs this but works without the daemon running

instprep() {
    echo -e ">>> Minifying install of ${PN}..."
    if [ ! -z "${ED}" ]; then
        rm -r "${ED}/etc"
        rm -r "${ED}/usr/sbin"
        rm -r "${ED}/usr/bin"
        rm -r "${ED}/lib/systemd"
        rm -r "${ED}/usr/share/dbus-1"
        rm -r "${ED}/usr/share/doc"
    fi
}

case "$1" in
    instprep) instprep ;;
    *) : ;;
esac
