#!/bin/sh

instprep() {
    if [ ! -z "${D}" ]; then
        echo -e "Setting up VPN Namespace by default for Steam..."
        mv "${D}/usr/bin/steam" "${D}/usr/lib/steam/steam"
        echo -e '#!/bin/bash'"\nexec vpn-run /usr/lib/steam/steam "'"$@"' > "${D}/usr/bin/steam"
        chmod +x "${D}/usr/bin/steam"
    fi
}

case "$1" in
    instprep) instprep ;;
    *) : ;;
esac
